#!/bin/bash 

if [ "$(id -u)" != "0" ]; then 
        sudo $0 $@
        exit 
fi

user=$SUDO_USER
if [[ "$user" == "" ]]; then 
	user=$(whoami)
fi

script="$(basename $0)"

function print_usage {
if [[ "$1" == "" ]]; then 
	cat <<HELP

usage:
	scan:
		$script 

	add:
		$script CONFIG_FILE ESSID [PASSWD]
HELP
	exit
fi

}

if [[ "$1" == "" ]]; then
	echo "searching for wireless networks..."
	iwlist wlan0 scan | grep -i essid | more
else
	conf_name="$1"
	essid="$2"
	passwd="$3"
	if [[ -z "$essid" ]]; then 
		print_usage
	fi

	# print and maybe save 
    if [[ -n "$passwd" ]]; then
    	wpa_passphrase "$essid" "$passwd" | tee "$conf_name"
    else
        cat <<EOL > "$conf_name"
network={
    ssid="$essid"
    key_mgmt=NONE
}
EOL
    fi
fi

