#!/bin/bash 

if [ "$(id -u)" != "0" ]; then 
	sudo $0 $@
	exit
fi

user=$SUDO_USER
if [[ "$user" == "" ]]; then 
	user=$(whoami)
fi

script="$(basename $0)"
if [[ "$1" == "" ]]; then 
	cat <<HELP

usage:
	connect:
		$script /path/to/wpa_passphrase-generated-config-file

	disconnect:
		$script stop
HELP
	exit
fi

conf_file=$1


echo "Stopping network manager"
/etc/init.d/network-manager stop 2> /dev/null
killall wpa_supplicant 2> /dev/null

if [ "$1" == "stop" ]; then 
	echo "disconnected frow wlan..."
	# we have disconnected earlier...
	exit 0
fi

essid=$(cat $conf_file | grep ssid | awk -F'=' '{print $2}' | sed "s/\"//g")
sleep 1
ifconfig wlp2s0 up 
found_essid=$(iwlist wlp2s0 scan | grep -i essid | grep $essid)
if [ "$found_essid" == "" ]; then 
	echo "WARNING: "
	echo "WARNING: "
	echo "WARNING: No wireless network is currently present named '$essid'"
	echo "WARNING: "
	echo "WARNING: "
fi

echo "connecting to wifi"
wpa_supplicant -c"$conf_file" -Dwext -iwlp2s0 &
sleep 5
dhclient wlp2s0

echo "all done..."

