#!/bin/bash 

if [ "$(id -u)" != "0" ]; then 
	sudo $0 $@
	exit
fi

user=$SUDO_USER
if [[ "$user" == "" ]]; then 
	user=$(whoami)
fi

script="$(basename $0)"
if [[ "$1" == "" ]]; then 
	cat <<HELP

usage:
	connect:
		$script /path/to/wpa_passphrase-generated-config-file

	disconnect:
		$script stop
HELP
	exit
fi

conf_file=$1


echo "Stopping network manager"
/etc/init.d/network-manager stop 2> /dev/null
killall wpa_supplicant 2> /dev/null

if [ "$1" == "stop" ]; then 
	echo "disconnected frow wlan..."
	# we have disconnected earlier...
	exit 0
fi

eth_ip="172.16.0.1/24"
ifconfig eth0:0 $eth_ip
echo "Using $eth_ip for eth0:0..."

echo "connecting to wifi"
wpa_supplicant -c"$conf_file" -Dwext -iwlan0 &
sleep 5
dhclient wlan0

echo "Making NAT configuration..."
echo "Clearing iptables"
iptables --table nat --flush 
iptables --flush 

iptables --table nat --append POSTROUTING --out-interface wlan0 -j MASQUERADE

iptables --append FORWARD --in-interface eth0:0 -j ACCEPT

echo 1 > /proc/sys/net/ipv4/ip_forward

echo "All settings are done, use $eth_ip as your gateway to connect to internet..."


