#!/bin/bash
set -eu -o pipefail
safe_source () { [[ ! -z ${1:-} ]] && source $1; _dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; _sdir=$(dirname "$(readlink -f "$0")"); }; safe_source
# end of bash boilerplate

show_help(){
    local script=$(basename $0)
    cat <<HELP

usage:
	connect:
		$script /path/to/wpa_passphrase-generated-config-file

	disconnect:
		$script stop
HELP
    exit
}

while :; do
    case $1 in
        -h|-\?|--help)
            show_help    # Display a usage synopsis.
            exit
            ;;
        *)               # Default case: No more options, so break out of the loop.
            break
    esac

    shift
done


[[ $(whoami) = "root" ]] || { sudo $0 $*; exit 0; }


WAN=$1
conf_file=$2

echo "Stopping network manager"
/etc/init.d/network-manager stop 2> /dev/null
killall wpa_supplicant 2> /dev/null

essid=$(cat $conf_file | grep ssid | awk -F'=' '{print $2}' | sed "s/\"//g")
sleep 1
ifconfig $WAN up
found_essid=$(iwlist $WAN scan | grep -i essid | grep $essid)
if [ "$found_essid" == "" ]; then 
	echo "WARNING: "
	echo "WARNING: No wireless network is currently present named '$essid'"
	echo "WARNING: "
fi

echo "connecting to wifi"
wpa_supplicant -c"$conf_file" -Dwext -i$WAN &
dhclient $WAN
wait
echo "all done..."

