#!/bin/bash

[[ "$1" = "" ]] && { echo "$(basename $0) [network_addr/XX or --all]"; exit; }

if [[ "$1" = "--all" ]]; then 
	NETWORK_ADDR=$(ip route | grep / | cut -d' ' -f1)
else
	NETWORK_ADDR="$@"
fi

echo "scanning network addr: $NETWORK_ADDR"
nmap -sP $NETWORK_ADDR
