#!/bin/bash
set -eu -o pipefail
safe_source () { [[ ! -z ${1:-} ]] && source $1; _dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; _sdir=$(dirname "$(readlink -f "$0")"); }; safe_source
# end of bash boilerplate

[[ $(whoami) = "root" ]] || { sudo $0 $*; exit 0; }

device=${1:-}

[[ -z $device ]] && { echo "First param. is device"; exit 1; }

echo "Renewing ip of $device"

# remove lease files
rm /var/lib/dhcp/dhclient* 2> /dev/null

get-ip(){
    /sbin/ifconfig $device | grep "inet addr:" | cut -d: -f2
}

while :; do
    ifdown $device
    ifup $device
    if [[ ! -z $(get-ip) ]]; then
        break
    fi
    echo "...retrying"
    sleep 5
done
echo "IP Renewed."
