#!/bin/bash
set -eu -o pipefail
safe_source () { [[ ! -z ${1:-} ]] && source $1; _dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; _sdir=$(dirname "$(readlink -f "$0")"); }; safe_source
# end of bash boilerplate

[[ $(whoami) = "root" ]] || { sudo $0 $*; exit 0; }

device=${1:-}

[[ -z $device ]] && { echo "First param. is device"; exit 1; }

echo "Renewing ip of $device"

# remove lease files
rm /var/lib/dhcp/dhclient* 2> /dev/null

while :; do
    dhclient -r $device
    dhclient $device
    if [[ $? -eq 0 ]]; then
        /etc/init.d/networking restart
        break
    fi
    echo "...retrying"
    sleep 2
done
echo "IP Renewed: "
ifconfig $device
